In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
df = pd.read_csv("games_pre.csv")

In [5]:
df.head()

            name             team  wins  losses  otl  total
0  Randy Carlyle    Anaheim Ducks    21      26    9     56
1     Bob Murray    Anaheim Ducks    14      11    1     26
2   Rick Tocchet  Arizona Coyotes    39      35    8     82
3  Bruce Cassidy    Boston Bruins    49      24    9     82
4   Phil Housley   Buffalo Sabres    33      39   10     82

In [4]:
df1 = pd.read_csv("teams.csv")
df1 = df1["Team"]
df1 = df1.values
df1 = df1.tolist()

In [6]:
arr = df.values

for i in range(0,37):
    arr[i][1] = df1.index(arr[i][1])+1

IndexError: index 36 is out of bounds for axis 0 with size 36

In [58]:
df1 = pd.read_csv("coaches.csv")
df1 = df1["Coach"]
df1 = df1.values
df1 = df1.tolist()

df2 = pd.read_csv("coaches_on_teams.csv")
df2 = df2["name"]
df2 = df2.values
df2 = df2.tolist()

In [77]:
arr = df2 = pd.read_csv("coaches_on_teams.csv")
arr = arr.values 
df1 = pd.read_csv("teams.csv")
df1 = df1["Team"]
df1 = df1.values
df1 = df1.tolist()
    
for i in range(0,37):
    arr[i][1] = df1.index(arr[i][1])+1

df1 = pd.read_csv("coaches.csv")
df1 = df1["Coach"]
df1 = df1.values
df1 = df1.tolist()

for i in range(0,37):
    arr[i][0] = df1.index(arr[i][0])+1
for i in range(0,46):
    print("INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (" + str(arr[i][0]) + "," + str(arr[i][1]) + "," + str(arr[i][5]) + "," + str(arr[i][2]) + "," + str(arr[i][3])+ "," + str(arr[i][4]) + ");" )

INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (29,1,56,21,26,9);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (35,1,26,14,11,1);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (24,2,82,39,35,8);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (7,3,82,49,24,9);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (34,4,82,33,39,10);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (19,5,82,50,25,7);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (6,6,82,46,29,7);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (20,7,15,6,6,3);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (8,7,67,30,28,9);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (2,8,82,38,30,14);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (25,9,82,47,31,4);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (18,10,82,43,32,7);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (4,11,82,32,40,10);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (17,12,82,35,38,9);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (28,13,82,36,32,14);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (36,14,13,4,8,1);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (31,14,69,27,34,8);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (5,15,82,37,36,9);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (14,16,82,44,30,8);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (15,17,82,47,29,6);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (13,18,82,31,41,10);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (26,19,82,48,27,7);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (21,20,82,32,36,14);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (27,21,64,22,37,5);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (30,21,18,7,10,1);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (33,22,31,12,15,4);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (32,22,51,25,22,4);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (23,23,82,44,26,12);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (10,24,82,46,27,9);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (37,25,19,7,9,3);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (3,25,63,38,19,6);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (9,26,82,62,16,4);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (1,27,82,46,28,8);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (12,28,82,35,36,11);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (11,29,82,43,32,7);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (22,30,82,48,26,8);
INSERT INTO Coaches_on_teams(fk_coach_id,fk_team_id,games_coached,wins,losses,otl) VALUES (16,31,82,47,30,5);

IndexError: index 37 is out of bounds for axis 0 with size 37

In [ ]:
#arr = pont[['Player','Age','Tm','Rk','Pos','GP','G','A','PTS','+/-','PIM','S','TOI','BLK','HIT']].values

#for i in range(0,1076):
        #arr[i][0] = arr[i][0][0:arr[i][0].find('/')]

In [ ]:
#arr
#for i in range(0,1076):
   # if(arr[i][2] != 'TOT'):
    #    print("INSERT INTO Players_on_teams(fk_player_id,fk_team_id,games_played,goals,assists,points,plus_minus,penalties_in_minutes,shots,time_on_ice,blocked_shots,hits) VALUES(" + str(arr[i][3]) + "," + str(arr[i][2]) + "," + str(arr[i][5]) + "," + str(arr[i][6]) + "," + str(arr[i][7])+ "," + str(arr[i][8]) + "," + str(arr[i][9])+ "," + str(arr[i][10])+ "," + str(arr[i][11])+ "," + str(arr[i][12])+ "," + str(arr[i][13])+ "," + str(arr[i][14]) + ");")

In [ ]:
#INSERT INTO games(game_date,fk_visitor_team_id,visitor_goals,fk_home_team_id,home_goals,type_of_win,attendance,len_of_game) VALUES (str_to_date('2019-04-06','%Y-%m-%d'),7,2,17,5,'REG',17694,'2:24');

In [ ]:
#arr = df.values
#for i in range(0,1270):
    #print("INSERT INTO games(fk_arena_id,game_date,fk_home_id,home_goal_total,fk_visitor_id,visitor_goal_total,type_of_win,attendance,length_of_game) VALUES (" + str(arr[i][3]) + ",'" + str(arr[i][0]) + "'," + str(arr[i][1]) + ","+ str(arr[i][2]) + ","+ str(arr[i][3]) + ","  + str(arr[i][4]) + ","+ str(arr[i][5]) + ","+ str(arr[i][6]) + ","+ str(arr[i][7])+  ");" )

In [ ]:
#arenas = pd.read_csv("arenas.csv")
#arr = arenas.values
#for i in range(0,31):
#    print("INSERT INTO Arenas(arena_name,capacity,year_opened) VALUES ('" + arr[i][0] + "'," + str(arr[i][2]) + "," + str(arr[i][3]) + ");")

In [ ]:
#goalies = pd.read_csv("goalies.csv")
#goalies = goalies[["Player","Age","GP","GS","W","L","GA","SA","SV","SO","MIN"]]
#arr = goalies.values
#for i in range(0,93):
    #print("INSERT INTO Goalies(goalie_name,age,games_played,games_started,wins,losses,goals_against,shots_against,saves,shut_outs,minutes) VALUES ('" + arr[i][0] + "'," + str(arr[i][1]) + "," + str(arr[i][2]) + "," + str(arr[i][3])+ "," + str(arr[i][4])+ "," + str(arr[i][5])+ ","+ str(arr[i][6])+ "," + str(arr[i][7]) +","+ str(arr[i][8])+ "," + str(arr[i][9])+ "," + str(arr[i][10]) +");")

In [ ]:
#teams = pd.read_csv("teams.csv")
#arr = teams.values
#for i in range(0,31):
#    print("INSERT INTO Teams(team_name,wins,losses,overtime_losses,points,goals_for,goals_against,power_plays,pp_goals,power_plays_against,ppa_goals,sh_goals,sh_goals_against,shots,shots_against,fk_arena_id) VALUES('" + arr[i][0] + "'," + str(arr[i][2])+ "," + str(arr[i][3])+ "," + str(arr[i][4])+ "," + str(arr[i][5])+ "," + str(arr[i][6])+ "," + str(arr[i][7])+ "," + str(arr[i][9])+ "," + str(arr[i][8])+ "," + str(arr[i][11])+ "," + str(arr[i][10])+ "," + str(arr[i][12])+ "," + str(arr[i][13])+ "," + str(arr[i][14])+ "," + str(arr[i][15])+ "," + str(arr[i][16])+ ");" )

In [ ]:
#players = pd.read_csv("players3.csv")
#arr = players.values

#for i in range(0,906):
#    arr[i][0] = arr[i][0].split('/')[0]

#for i in range(0,906):
#    print("INSERT INTO Players(player_name,age,position,games_played,goals,assists,points,plus_minus,penalties_in_minutes,shots,time_on_ice,blocked_shots,hits) VALUES('" + str(arr[i][0]) + "'," + str(arr[i][1]) + ",'"+ str(arr[i][2]) + "',"+ str(arr[i][3]) + ","+ str(arr[i][4]) + ","+ str(arr[i][5]) + "," + str(arr[i][6]) + ","+ str(arr[i][7]) + ","+ str(arr[i][8]) + ","+ str(arr[i][9]) + "," + str(arr[i][10]) + ","+ str(arr[i][11]) + "," + str(arr[i][12]) + ");")

In [ ]:
#goalies = pd.read_csv("goalies_on_teams.csv")
#arr = goalies.values

#for i in range(0,107):
    #arr[i][1] = arr[i][1].split('/')[1]

#for i in range(0,107):
    #if(arr[i][3] != 'TOT'):
       # print("INSERT INTO goalies_on_teams(fk_goalie_id,fk_team_id,games_played,games_started,wins,losses,goals_against,shots_against,saves,shut_outs,minutes) VALUES(" + str(arr[i][0]) + "," + str(arr[i][3]) + ","+ str(arr[i][4]) + ","+ str(arr[i][5]) + ","+ str(arr[i][6]) + ","+ str(arr[i][7]) + "," + str(arr[i][8]) + ","+ str(arr[i][9]) + ","+ str(arr[i][10]) + ","+ str(arr[i][11]) + "," + str(arr[i][12])  + ");")

In [1]:
#coaches = pd.read_csv("coaches.csv")
#arr = coaches.values
#for i in range(0,46):
    #print("INSERT INTO Coaches(coach_name,games_coached,wins,losses,first_year_coaching,latest_year_coaching,stanley_cups_won) VALUES ('" + arr[i][0] + "'," + str(arr[i][4]) + "," + str(arr[i][5]) + "," + str(arr[i][6]) + "," + str(arr[i][1]) + "," + str(arr[i][2]) + "," + str(arr[i][7]) + ");" )

In [ ]:
#gms = pd.read_csv("general managers.csv")
#arr = gms.values
#for i in range(0,31):
#    print("INSERT INTO General_Managers(gm_name,tendered_since) VALUES ('" + arr[i][0] + "','" + str(arr[i][1]) + "');")

In [ ]:
#awards = pd.read_csv("awards.csv")
#arr = awards.values
#for i in range(0,14):
    #print("INSERT INTO Awards(name_of_award,winner,description_of_award) VALUES ('" + arr[i][0] + "','" + arr[i][1] + "','" + arr[i][2] + "');")

In [9]:
games = pd.read_csv("games_pre.csv")
arr = games.values
for i in range(0,1271):
    print("INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('" + arr[i][0] + "'," + str(arr[i][1]) + "," + str(arr[i][2]) + "," + str(arr[i][3]) + "," + str(arr[i][4]) + ",'" + str(arr[i][5]) + "'," + str(arr[i][6]) + "," + str(arr[i][7]) + ");")

INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-03',1,5,24,2,'REG',17562,145);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-03',16,2,27,3,'OT',19589,157);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-03',5,2,28,5,'REG',18870,151);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-03',3,0,30,7,'REG',18506,150);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-04',3,4,4,0,'REG',19070,155);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-04',19,2,6,1,'OT',18680,154);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-04',15,1,8,4,'REG',18086,157);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-04',2,0,10,3,'REG',18532,154);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-04',9,3,11,2,'OT',19515,163);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-04',17,3,20,2,'REG',17117,151);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-04',7,4,21,3,'OT',15858,158);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-04',30,6,23,7,'OT',18627,159);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-04',31,5,25,1,'REG',18292,155);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-04',22,5,29,2,'REG',18555,144);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-05',6,3,9,1,'REG',18306,155);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-05',24,3,14,2,'OT',18230,156);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-06',1,1,2,0,'REG',17125,144);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-06',20,1,4,3,'REG',16824,165);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-06',28,4,5,7,'REG',18688,159);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-06',22,2,8,5,'REG',16768,153);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-06',31,1,10,5,'REG',18131,156);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-06',29,2,15,1,'SO',19077,198);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-06',12,2,18,5,'REG',12044,151);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-06',17,4,19,3,'REG',12163,145);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-06',16,5,23,1,'REG',18622,146);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-06',7,5,25,4,'OT',17429,159);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-06',13,1,26,2,'SO',19092,159);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-06',21,5,27,3,'REG',19321,155);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-07',20,5,6,8,'REG',13526,157);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-07',27,7,7,6,'OT',21812,151);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-07',11,2,14,4,'REG',18230,163);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-08',11,2,1,3,'SO',17436,164);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-08',21,3,3,6,'REG',17565,153);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-08',29,2,4,4,'REG',16004,140);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-08',24,0,19,4,'REG',8790,146);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-09',28,3,6,5,'REG',11932,155);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-09',8,2,9,5,'REG',11694,147);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-09',27,7,10,4,'REG',17866,150);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-09',5,3,17,0,'REG',17209,152);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-09',24,8,22,2,'REG',19133,154);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-09',14,1,31,2,'REG',15321,147);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-10',2,3,1,2,'SO',17015,150);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-10',22,7,21,4,'REG',13215,158);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-10',29,2,30,5,'REG',18506,160);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-11',12,1,3,4,'REG',17565,148);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-11',8,6,4,1,'REG',15396,150);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-11',27,5,11,3,'REG',19515,152);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-11',9,5,13,4,'REG',14394,154);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-11',7,3,15,4,'OT',18652,162);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-11',14,3,16,0,'REG',21302,153);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-11',30,0,18,6,'REG',16514,151);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-11',31,0,17,3,'REG',17228,150);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-11',24,2,20,3,'OT',17004,151);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-11',29,2,23,4,'REG',18610,147);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-11',5,3,25,5,'REG',16403,157);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-11',28,4,26,1,'REG',19092,143);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',4,3,2,0,'REG',15304,152);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',11,2,3,8,'REG',17565,160);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',25,3,7,4,'OT',21634,158);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',5,3,8,2,'OT',17334,154);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',1,3,10,5,'REG',18532,158);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',28,3,13,2,'REG',11953,152);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',6,5,15,4,'OT',18715,176);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',23,3,16,4,'SO',21302,203);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',19,2,17,5,'REG',17208,154);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',12,2,20,1,'REG',17085,144);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',14,1,21,5,'REG',15355,149);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',29,1,22,0,'REG',19067,139);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',9,2,26,8,'REG',19092,156);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-13',27,4,30,2,'REG',18506,141);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-14',24,2,18,3,'REG',13809,155);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-14',1,3,25,2,'REG',16562,156);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-14',6,1,31,3,'REG',15321,153);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-15',11,3,16,7,'REG',20323,160);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-15',15,2,17,4,'REG',17165,152);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-15',10,1,21,4,'REG',12358,150);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-15',14,1,27,4,'REG',19429,145);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-16',2,1,15,2,'REG',18795,155);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-16',10,0,18,3,'REG',12808,153);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-16',8,2,20,3,'SO',17251,163);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-16',13,5,22,6,'SO',19038,168);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-16',28,3,23,2,'OT',18492,144);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-16',6,2,26,4,'REG',19092,157);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-16',4,1,29,4,'REG',18321,158);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-16',12,5,31,4,'OT',15321,149);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-17',19,1,1,4,'REG',16909,150);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-17',3,2,5,5,'REG',17641,145);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-17',25,2,16,3,'REG',20137,142);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-17',20,3,30,4,'OT',18506,154);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-18',22,3,9,6,'REG',13492,140);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-18',2,4,7,1,'REG',21210,151);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-18',3,2,12,3,'OT',18347,146);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-18',19,7,14,2,'REG',18230,154);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-18',8,5,18,3,'REG',13374,161);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-18',4,1,24,5,'REG',17389,153);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-18',11,1,26,3,'REG',19092,163);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-18',23,3,27,0,'REG',19483,148);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-18',28,1,31,4,'REG',15321,152);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-19',17,5,5,3,'REG',18725,156);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-19',15,3,10,1,'REG',18346,138);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-19',13,6,30,5,'SO',18506,176);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',8,3,6,1,'REG',11753,150);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',7,4,9,1,'REG',17005,149);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',17,3,12,0,'REG',18347,149);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',11,4,13,3,'OT',14534,164);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',4,5,14,1,'REG',18230,158);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',26,4,15,5,'OT',19080,162);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',16,3,21,4,'OT',18442,157);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',18,2,22,5,'REG',19105,155);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',19,1,24,4,'REG',17414,151);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',25,4,27,1,'REG',19268,151);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',3,1,28,2,'OT',17871,150);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',1,1,29,3,'REG',18375,153);
INSERT INTO Games(game_date,fk_visitor_id,visitor_goal_total,fk_home_id,home_goal_total,type_of_win,attendance,length_of_game) VALUES ('2018-10-20',2,3,31,5,'REG',15321,153);

In [30]:
df1 = pd.read_csv("teams.csv")
df1 = df1["Team"]
df1 = df1.values
df1 = df1.tolist()
for i in range(0,217):
    arr[i][1] = df1.index(arr[i][1])+1

In [46]:
drafts = pd.read_csv("draft.csv")
arr = drafts.values
for i in range(0,217):
    arr[i][2] = arr[i][2].split("/")[0]
df1 = pd.read_csv("teams.csv")
df1 = df1["Team"]
df1 = df1.values
df1 = df1.tolist()
for i in range(0,217):
    arr[i][1] = df1.index(arr[i][1])+1
for i in range(0,217):
    print("INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (" + str(arr[i][0]) + "," + str(arr[i][1]) + ",'" + str(arr[i][2]) + "','" + str(arr[i][3])  + "','" + str(arr[i][4])  + "'," + str(arr[i][5])   + ",'" + str(arr[i][6]) + "');" )

INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (1,18,'Jack Hughes','US','C',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (2,20,'Kaapo Kakko','FI','RW',18,'TPS (Finland)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (3,7,'Kirby Dach','CA','C',18,'Saskatoon Blades (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (4,8,'Bowen Byram','CA','D',18,'Vancouver Giants (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (5,14,'Alex Turcotte','US','C',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (6,11,'Moritz Seider','DE','D',18,'Mannheim (GERMANY)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (7,4,'Dylan Cozens','CA','C',18,'Lethbridge Hurricanes (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (8,12,'Philip Broberg','SE','D',18,'AIK (Sweden-2)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (9,1,'Trevor Zegras','US','C',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (10,28,'Vasily Podkolzin','RU','RW',18,'SKA-Neva St. Petersburg (RUSSIA-2)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (11,2,'Victor Soderstrom','SE','D',18,'Brynas IF (Sweden)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (12,15,'Matthew Boldy','US','LW',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (13,13,'Spencer Knight','US','G',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (14,22,'Cameron York','US','D',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (15,16,'Cole Caufield','US','RW',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (16,8,'Alex Newhook','CA','C',18,'Victoria (BCHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (17,29,'Peyton Krebs','CA','C',18,'Kootenay Ice (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (18,10,'Thomas Harley','US','D',18,'Mississauga Steelheads (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (19,21,'Lassi Thomson','FI','D',18,'Kelowna Rockets (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (20,31,'Ville Heinola','FI','D',18,'Lukko (Finland)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (21,23,'Samuel Poulin','CA','RW',18,'Sherbrooke Phoenix (QMJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (22,14,'Tobias Bjornfot','SE','D',18,'Djurgardens Jr. (Sweden-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (23,19,'Simon Holmström','SE','RW',18,'HV 71 Jr. (Sweden-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (24,17,'Philip Tomasino','CA','C',18,'Niagara (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (25,30,'Connor McMichael','CA','C',18,'London Knights (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (26,5,'Jakob Pelletier','CA','LW',18,'Moncton Wildcats (QMJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (27,26,'Nolan Foote','US','LW',18,'Kelowna Rockets (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (28,6,'Ryan Suzuki','CA','C',18,'Barrie Colts (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (29,1,'Brayden Tracey','CA','LW',18,'Moose Jaw Warriors (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (30,3,'John Beecher','US','C',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (31,4,'Ryan Johnson','US','D',18,'Sioux Falls (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (32,21,'Shane Pinto','US','C',18,'Tri-City (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (33,14,'Arthur Kaliyev','UZ','RW',18,'Hamilton Bulldogs (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (34,22,'Bobby Brink','US','RW',18,'Sioux City (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (35,11,'Antti Tuomisto','FI','D',18,'Assat Jr. (Finland-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (36,6,'Pyotr Kochetkov','RU','G',20,'HK Ryazan (RUSSIA-2)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (37,21,'Mads Sogaard','DK','G',18,'Medicine Hat Tigers (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (38,12,'Raphael Lavoie','CA','C',18,'Halifax Mooseheads (QMJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (39,1,'Jackson LaCombe','US','D',18,'Shattuck - St. Mary's Prep (High-MN)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (40,28,'Nils Hoglander','SE','LW',18,'Rogle (Sweden)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (41,29,'Kaedan Korczak','CA','D',18,'Kelowna Rockets (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (42,15,'Vladislav Firstov','RU','LW',18,'Waterloo (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (43,7,'Alex Vlasic','US','D',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (44,6,'Jamieson Rees','CA','C',18,'Sarnia Sting (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (45,17,'Egor Afanasyev','RU','LW',18,'Muskegon (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (46,16,'Jayden Struble','US','D',18,'St. Sebastian's School (High-MA)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (47,8,'Drew Helleson','US','D',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (48,24,'Artemi Kniazev','RU','D',18,'Chicoutimi Sagueneens (QMJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (49,20,'Matthew Robertson','CA','D',18,'Edmonton Oil Kings (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (50,14,'Samuel Fagemo','SE','LW',19,'Frolunda (Sweden)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (51,31,'Simon Lundmark','SE','D',18,'Linkoping Jr. (Sweden-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (52,13,'Vladislav Kolyachonok','BY','D',18,'Flint Firebirds (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (53,27,'Nicholas Robertson','US','LW',18,'Peterborough Petes (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (54,11,'Robert Mastrosimone','US','LW',18,'Chicago (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (55,24,'Dillon Hamaliuk','CA','LW',18,'Seattle Thunderbirds (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (56,30,'Brett Leason','CA','RW',20,'Prince Albert Raiders (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (57,19,'Samuel Bolduc','CA','D',18,'Blainville-Boisbriand Armada (QMJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (58,20,'Karl Henriksson','SE','C',18,'Frolunda Jr. (Sweden-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (59,15,'Hunter Jones','CA','G',18,'Peterborough Petes (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (60,11,'Albert Johansson','SE','D',18,'Farjestad Jr. (Sweden-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (61,18,'Nikita Okhotyuk','RU','D',18,'Ottawa 67's (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (62,25,'Nikita Alexandrov','DE','C',18,'Charlottetown Islanders (QMJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (63,8,'Matthew Stienburg','CA','C',18,'St. Andrews College (HIGH-ON)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (64,16,'Mattias Norlinder','SE','D',19,'MODO Jr. (Sweden-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (65,17,'Alexander Campbell','CA','LW',18,'Victoria (BCHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (66,11,'Albin Grewe','SE','RW',18,'Djurgardens Jr. (Sweden-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (67,4,'Erik Portillo','SE','G',19,'Frolunda Jr. (Sweden-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (68,20,'Zachary Jones','US','D',18,'Tri-City (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (69,13,'John Ludvig','CZ','D',19,'Portland Winter Hawks (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (70,18,'Daniil Misyul','BY','D',18,'Yaroslaval 2 (Russia-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (71,26,'Hugo Alnefelt','SE','G',18,'HV 71 Jr. (Sweden-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (72,22,'Ronald Attard','US','D',20,'Tri-City (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (73,6,'Patrick Puistola','FI','RW',18,'Tappara Jr. (Finland-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (74,23,'Nathan Legare','CA','RW',18,'Baie-Comeau Drakkar (QMJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (75,15,'Adam Beckman','CA','LW',18,'Spokane Chiefs (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (76,2,'John Farinacci','US','C',18,'Dexter School (High-MA)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (77,16,'Gianni Fairbrother','CA','D',18,'Everett Silvertips (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (78,8,'Alex Beaucage','CA','RW',18,'Rouyn-Noranda Huskies (QMJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (79,29,'Pavel Dorofeyev','RU','LW',18,'Magnitogorsk (Russia)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (80,18,'Graeme Clarke','US','RW',18,'Ottawa 67's (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (81,13,'Cole Schwindt','CA','RW',18,'Mississauga Steelheads (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (82,18,'Michael Vukojevic','CA','D',18,'Kitchener Rangers (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (83,6,'Anttoni Honka','FI','D',18,'Jukurit (Finland)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (84,27,'Mikko Kokkonen','FI','D',18,'Jukurit (Finland)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (85,12,'Ilya Konovalov','RU','G',21,'Yaroslaval (Russia)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (86,29,'Layton Ahac','CA','D',18,'Prince George (BCHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (87,14,'Lukas Parik','CZ','G',18,'Liberec Jr. (Czech-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (88,5,'Ilya Nikolaev','RU','C',18,'Yaroslaval 2 (Russia-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (89,26,'Maxim Cajkovic','SK','RW',18,'Saint John Sea Dogs (QMJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (90,6,'Domenick Fensore','US','D',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (91,30,'Aliaksei Protas','BY','C',18,'Prince Albert Raiders (WHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (92,3,'Quinn Olson','CA','LW',18,'Okotoks (AJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (93,25,'Colten Ellis','CA','G',18,'Rimouski Oceanic (QMJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (94,21,'Viktor Lodin','SE','C',20,'Orebro (Sweden)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (95,14,'Jordan Spence','AU','D',18,'Moncton Wildcats (QMJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (96,18,'Tyce Thompson','US','RW',20,'Providence (H-East)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (97,11,'Ethan Phillips','CA','C',18,'Sioux Falls (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (98,2,'Matias Maccelli','FI','LW',18,'Dubuque (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (99,6,'Cade Webber','US','D',18,'Rivers Academy (High-MA)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (100,12,'Matej Blumel','CZ','RW',19,'Waterloo (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (101,1,'Henry Thurn','US','D',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (102,4,'Aaron Huglen','US','RW',18,'Roseau (High-MN)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (103,22,'Mason Millman','CA','D',18,'Saginaw Spirit (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (104,9,'Eric Hjorth','SE','D',18,'Linkoping Jr. (Sweden-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (105,7,'Michael Teply','CZ','LW',18,'Benatky N.J. (Czech-2)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (106,13,'Carter Berger','CA','D',19,'Victoria (BCHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (107,2,'Alexandr Darin','RU','RW',19,'Yaroslaval 2 (Russia-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (108,24,'Yegor Spiridonov','RU','C',18,'Magnitogorsk 2 (Russia-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (109,17,'Marc Del Gaizo','US','D',19,'Massachusetts-Lowell (H-East)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (110,29,'Ryder Donovan','US','C',18,'Duluth East (High-MN)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (111,10,'Samuel Sjolund','SE','D',18,'AIK Jr. (Sweden-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (112,20,'Hunter Skinner','US','D',18,'Lincoln (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (113,31,'Henri Nikkanen','FI','C',18,'Jukurit Jr. (Finland-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (114,9,'Dimitri Voronkov','RU','LW',19,'Bars Kazan (RUSSIA-2)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (115,27,'Mikhail Abramov','RU','C',18,'Victoriaville Tigres (QMJHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (116,5,'Lucas Feuk','SE','LW',18,'Sodertalje Jr. (Sweden-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (117,17,'Semyon Chystyakov','RU','D',18,'UFA 2 (Russia-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (118,18,'Case McCarthy','US','D',18,'USA U-18 (U.S. NTDP)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (119,14,'Kim Nousianinen','FI','D',18,'Kalpa Jr. (Finland-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (120,26,'Maxwell Crozier','CA','D',19,'Sioux Falls (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (121,6,'Tuukka Tieksola','FI','RW',18,'Karpat Jr. (Finland-Jr.)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (122,28,'Ethan Keppen','CA','LW',18,'Flint Firebirds (OHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (123,7,'Antti Saarela','FI','C',18,'Lukko (Finland)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (124,27,'Nicholas Abruzzese','US','C',20,'Chicago (USHL)');
INSERT INTO Draft_Picks(overall,fk_team_id,draftee_name,nationality,pos,age,amateur_team) VALUES (125,21,'Mark Kastelic','US','C',20,'Calgary Hitmen (WHL)');